### ISSUE TITLE
FE - Game List Rating Set to 1 decimal.

### ISSUE THREAD

**Issue by ptatro** [ptatro/trivia-platoon-frontend#18]

**Comment by cnikolai** [comment]
<img width="1748" alt="Screen Shot 2021-09-30 at 7 51 18 PM" src="https://user-images.githubusercontent.com/23004679/135545716-3fb0c05a-4406-4cde-b554-4be1bf463a15.png">

**Comment by cnikolai** [comment]
Can we limit the rating decimal to 1 digit?
